[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://millenniumsi.sharepoint.com"
    Content-Security-Policy = "frame-ancestors 'self' https://millenniumsi.sharepoint.com"
